### ISSUE TITLE
Add temporal extent extraction for GML

### ISSUE THREAD

**Issue by nuest** [o2r-project/geoextent#106]
See skipped test at https://github.com/o2r-project/geoextent/pull/99/files#diff-4e8715c7a425ee52e74b7df4d34efd32e8c92f3e60bd51bc2e1ad5943b82032eR204

**Comment by SbastianGarzon** [comment]
Already implemented by #99 
[Test](https://github.com/o2r-project/geoextent/blob/c41560fc8456c80d79ed4321274a525d69d6b8c7/tests/test_api.py#L129)
