### ISSUE TITLE
Implement temporal_extent extraction of .csv

### ISSUE THREAD

**Issue by YouQam** [o2r-project/geoextent#20]

**Comment by nuest** [comment]
Currently supported column names: `time`, `timestamp`

- [ ] Support other names:
  - `date`
  - `datetime`
- [ ] normalise column names before checking (to lower case, remove delimiters) and add test for different cases, e.g. `Time`, `TimeStamp`, `TIME`, `Date` etc.
- [ ] log a warning if more than one column was found (e.g. `date` AND `time`), then only use one of them

**Comment by YouQam** [comment]
There is a bug in getting time interval due to including headers.

![Screenshot from 2020-02-28 00-45-06](https://user-images.githubusercontent.com/40634685/75503850-21e94d80-59d7-11ea-9351-5aed4bff3117.png)

**Comment by YouQam** [comment]
When more than one column was found, it takes the first one. As in the test case: https://github.com/YouQam/geoextent/commit/1a4934ee75c3eba3790794addafc2911825272b7

**Comment by nuest** [comment]
@YouQam For the test in https://github.com/YouQam/geoextent/commit/1a4934ee75c3eba3790794addafc2911825272b7 to actually test something, wouldn't it be good if the `DATE` column had different values, so you are sure the `TIME` column is chosen?

**Comment by YouQam** [comment]
> @YouQam For the test in [YouQam@1a4934e](https://github.com/YouQam/geoextent/commit/1a4934ee75c3eba3790794addafc2911825272b7) to actually test something, wouldn't it be good if the `DATE` column had different values, so you are sure the `TIME` column is chosen?

Sure about it and I will change values to be more sure.

**Comment by YouQam** [comment]
dataset has been changed. https://github.com/YouQam/geoextent/commit/7f021d34b52ccc419f4bfcb62a63a8ad9dc67de2
