### ISSUE TITLE
Add support for GeoTIFF

### ISSUE THREAD

**Issue by nuest** [o2r-project/geoextent#23]
Test file: https://github.com/o2r-project/geoextent/blob/master/tests/testdata/wf_100m_klas.tif

**Comment by nuest** [comment]
Re. timestamps, maybe these links help:

- https://gis.stackexchange.com/questions/291554/retrieving-exif-tags-from-geotiff-with-gdal
- https://github.com/OSGeo/gdal/issues/828
- https://gdal.org/drivers/raster/gtiff.html - see `TIFFTAG_DATETIME`

**Comment by YouQam** [comment]
This issue is done but I don't have permission to close it. Can you do it?
