### ISSUE TITLE
Improve handler and file format detection

### ISSUE THREAD

**Issue by nuest** [o2r-project/geoextent#28]
As of now, there is an "if else" chain checking and selecting suitable handlers. The concept of a handler is great, but instead of a fixed chain, we should have a list of handlers, and each handler can decide if they "take" the format because they support it, or if they don't.

See a working example of such a mechanism here: 

1. import all handlers (in this case they are called `contentproviders`): https://github.com/jupyter/repo2docker/blob/master/repo2docker/app.py#L41
1. put them all in a list: https://github.com/jupyter/repo2docker/blob/master/repo2docker/app.py#L144
1. iterate through the list until one handler returns `True` in the `detect()` function.

For this to work, we need a class `FormatHandler`, sketched here (roughly based on [`ContentProvider`](https://github.com/jupyter/repo2docker/blob/master/repo2docker/contentproviders/base.py#L17)):

```python
class FormatHandler:
    def __init__(self):
        self.log = logging.getLogger("geoextent")

    def detect(self, file):
        """Determine compatibility between source and this hanlder.
        If the handler knows how to extract geospatial and temporal extent,
        it will return `True`.
        If the provider does not know how to fetch this source it will return
        `False`.
        """
        raise NotImplementedError()

    def bbox(self, file):
        """Get the geospatial extent of given file.
        """
        raise NotImplementedError()

    def time(self, file):
        """Get the temporal extent of given file.
        """
        raise NotImplementedError()

```

Based on this abstract class, we can implement the respective handlers (pseudo code!):

```python
class GeojsonFormatHandler(FormatHandler):
    def detect(self, file):
        if os.path.splitext(filePath) == "json" or == "geojson":
            check if the content is GeoJSON, maybe by trying to parse it as such? or is there another clever way to make the detection based on the _content_ ?

    [... implement functions ...]
```

**Comment by YouQam** [comment]
I used dict where key is file format and value is the module.

**Comment by YouQam** [comment]
I used another way to do it, but the issue is`remaining open`.

I used a dictionary that holds file format as a `key` and module as a `value`. After file format is extracted is goes through a loop of all keys to get the suitable module to handle the file.
```
modulesSupported = {'geojson':handleGeojson, 'json':handleGeojson,'csv':handleCSV,
    'shp':handleShapefile, 'dbf':handleShapefile, 'geotiff':handleGeotiff, 'tif':handleGeotiff}

    # get the module that will be called (depending on the format of the file)
    for key in modulesSupported.keys():
        if key == fileFormat:
            print(key)
            usedModule = modulesSupported.get(key)
```

**Comment by nuest** [comment]
Get rid of the `modulesSupported` object in https://github.com/o2r-project/geoextent/blob/master/geoextent/lib/extent.py#L12
