### ISSUE TITLE
Add function to print list of supported formats to console

### ISSUE THREAD

**Issue by nuest** [o2r-project/geoextent#29]
```bash
$ geoextent --formats
Shapefile
GeoTIFF
GeoJSON
```

**Comment by YouQam** [comment]
You added this in last pull request, should I do it in a defferent way?
```
Supported formats:
- GeoJSON (.geojson)
- Tabular data (.csv)
- Shapefile (.shp)
- GeoTIFF (.geotiff, .tif)
```

**Comment by nuest** [comment]
These are two different things. I was talking about a CLI command, and you copy and pasted the content of the help text, right?

**Comment by YouQam** [comment]
> These are two different things. I was talking about a CLI command, and you copy and pasted the content of the help text, right?

Got it. Yes, I wanted to be sure about it.

**Comment by YouQam** [comment]
The error was occurring due to missing dash before `input` argument,

```
       parser.add_argument(
        '--input',
        action=readable_file_or_dir,
        default=os.getcwd(),
        nargs='+',
        help="input file or path"
    )
```

**Comment by YouQam** [comment]
Close
