### ISSUE TITLE
Handling CSV files separated by either semicolon or comma

### ISSUE THREAD

**Issue by YouQam** [o2r-project/geoextent#34]
Now the default is separated by comma and doesn't work when separated by semicolon.

Adding delimiter with semicolon makes doesn't work when separated by comma.
```
daten = csv.reader(csv_file.readlines(), delimiter=';')
```
The solution can be using pandas, where mutliple delimiters can be added,  
- https://stackoverflow.com/questions/41847146/multiple-delimiters-in-single-csv-file

**Comment by nuest** [comment]
> Adding delimiter with semicolon makes doesn't work when separated by comma.

Than can be expected.

We don't need to support multiple delimiters in the same file. I suggest instead to look in the first line of the CSV file and then use the first delimiter that appears on it as a simple detection method. That should work in most cases!

**Comment by YouQam** [comment]
I solved the issue using delimiters detection, 
- https://stackoverflow.com/questions/15093952/how-to-use-csv-sniffer-for-2-different-csv-types
