### ISSUE TITLE
(CSV) Time column names matches.

### ISSUE THREAD

**Issue by SbastianGarzon** [o2r-project/geoextent#81]
Time extraction only works if column name exactly matches "timestamp", "datetime", "time" or "date".

**Comment by SbastianGarzon** [comment]
The matches should not have to be exact. For example ("probe time", "observation date", "time_stamp", "observation_timestamp", ...) should be extracted to determine the time extent of the file.

**Comment by nuest** [comment]
The matching function should be reusable across handlers, so that we can use the same list of names for example to identify column names in non-tabular data, e.g. #16
