### ISSUE TITLE
(CSV) Enable time extraction of more than one column.

### ISSUE THREAD

**Issue by SbastianGarzon** [o2r-project/geoextent#82]
Geoextent only extracts one column with 'date' information. Some experiments record  start and end of a measurement, for this reason is relevant to take into account more than one column with 'date' information to extract the real time extent.

**Comment by nuest** [comment]
Good point! We will have to add a few keywords ("begin", "end", "start") to the list and then throw the values of these columns all in bucket to find min and max.
