### ISSUE TITLE
Add support for Sentinel-2 SENTINEL-SAFE

### ISSUE THREAD

**Issue by nuest** [o2r-project/geoextent#84]
https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-2-msi/data-formats

**Comment by nuest** [comment]
Probably already supported via raster handler - add a test and see!

**Comment by SbastianGarzon** [comment]
#99 and #122 covers XML and JPEG2000 Files. Therefore Sentinel-2 SENTINEL-SAFE data is covered by geoextent.
