### ISSUE TITLE
Add support for JPEG2000

### ISSUE THREAD

**Issue by nuest** [o2r-project/geoextent#85]
- https://gdal.org/drivers/raster/jpeg2000.html

Possibly required for #84 

The image might have timestamps that could be used for temporal extraction.

- [x] geospatial extent implemented (+ tests)
- [ ] temporal extent implemented (+ tests)

**Comment by nuest** [comment]
@SbastianGarzon If the raster handler based on GDAL really works that well as discussed today, maybe this is too easy not to do?

**Comment by SbastianGarzon** [comment]
Issue closed (spatial extent extraction), extraction of the temporal extent will be handle by #123
